### ISSUE TITLE
SVO appears to be down and unavailable - can we bypass an alternative Observatory for getting lightband filters?

### ISSUE THREAD

**Issue by wakatara** [guillochon/MOSFiT#190]
New user of MOSFIT so forgive me if this is answered elsewhere. 

Running the software to generate lightcurves with the `default` model appears to be throwing errors that the SVO is down with a 

> Secure Connection Failed
>
> An error occurred during a connection to svo.cab.inta-csic.es. PR_END_OF_FILE_ERROR
>
>    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>    Please contact the website owners to inform them of this problem.

when I try to reach the site manually after looking in the source code for the pull. 

I realize this is an upstream issue from the code (I sent a note to the only contact name I could find online for the SVO to resolve it, but it seems like it may have been down for a while.). 

Is there another way to pull the data from one of the other virtual observatories and can that be passed as a parameter?

**Comment by wakatara** [comment]
For the precise errors, this is what was received:

`RuntimeError: cant_read_svo`

and the following output...

``` bash
Found event by primary name `SN1993J` in the `OSC`, downloading data...

Event file:
  /usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/cache/SN1993J.json

Basic model file:
  /usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/models/model.json
Model file:
  /usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/models/csmni/csmni.json
Parameter file:
  models/csmni/parameters.json

Loading module `fitlc` [ 98% ]
Warning: The following wavebands are not supported by the model used to fit this data: `infrared,
optical, ultraviolet`, and have been excluded from the fitting process. To include these bands
anyway (although it is not recommended), add `--exclude-kinds none` to your command.


Downloading bandpass `Subaru/HSC.i2_filter/AB` from SVO...
Warning: Could not download SVO filter (are you online?), using cached filter.
Failed to execute module `photometry`'s process().
Traceback (most recent call last):
  File "/usr/local/bin/mosfit", line 33, in <module>
    sys.exit(load_entry_point('mosfit==1.1.8', 'console_scripts', 'mosfit')())
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/main.py", line 973, in main
    Fitter(**fitargs).fit_events(**fitargs)
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/fitter.py", line 388, in fit_events
    success = self._model.load_data(
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/model.py", line 452, in load_data
    outputs = self.run_stack(
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/model.py", line 970, in run_stack
    new_outs = self._modules[task].process(**inputs)
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/modules/observables/photometry.py", line 435, in process
    self.preprocess(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/modules/observables/photometry.py", line 430, in preprocess
    self.load_bands(kwargs['all_band_indices'])
  File "/usr/local/lib/python3.9/site-packages/mosfit-1.1.8-py3.9.egg/mosfit/modules/observables/photometry.py", line 272, in load_bands
    raise RuntimeError(
RuntimeError: cant_read_svo

```

**Comment by mnicholl** [comment]
Hi Daryl, it looks like SVO is back up (at least it works fine for me). If you need a temporary solution, I have a big folder full of filter profiles that have built up from various mosfit runs. If you put these in <run directory>/modules/observables/filters, and run mosfit with the flag --prefer-cache, it should use the local filters rather than trying to query SVO.

https://www.dropbox.com/sh/44pwu9pyxhq2tnx/AABOkpvolcbQ21t55ozHyXOYa?dl=0
