### ISSUE TITLE
Constructing output failed

### ISSUE THREAD

**Issue by Brookluo** [guillochon/MOSFiT#197]
Hi, I met an issue when MOSFit was generating output. All the fitting process was successful, but I got this error message during constructing output. 

```Python
Constructing output...
Traceback (most recent call last):
  File "/d/users/brook/.conda/envs/py37/bin/mosfit", line 10, in <module>
    sys.exit(main())
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/mosfit/main.py", line 973, in main
    Fitter(**fitargs).fit_events(**fitargs)
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/mosfit/fitter.py", line 498, in fit_events
    extra_outputs=extra_outputs)
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/mosfit/fitter.py", line 603, in fit_data
    compare_to_existing=False)
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/astrocats/catalog/entry.py", line 676, in init_from_file
    filter_on=filter_on)
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/astrocats/catalog/entry.py", line 324, in _load_data_from_json
    filter_on=filter_on)
  File "/d/users/brook/.conda/envs/py37/lib/python3.7/site-packages/astrocats/catalog/entry.py", line 480, in _convert_odict_to_classes
    **vv)
TypeError: _add_cat_dict() argument after ** must be a mapping, not str
```

The version of astrocats I am using is 0.3.37 (I believe is the most recent one). Python==3.7.12, mosfit==1.1.8. I was fitting private data. The data is formatted according to OAC schema. 
I was wondering if this issue is caused by astrocats?
Any help or suggestion on how to solve this issue will be greatly appreciated! 

Thanks,
Brook

**Comment by Yanshengyu0311** [comment]
I have the same error when fitting the pravite data.
