### ISSUE TITLE
Must specify event in Version 0.3.0 (e347ae48e856fb14)

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#46]
When I try to run:

python -m mosfit -m default 

I get the following error:

No handlers could be found for logger "root"
Traceback (most recent call last):
  File "/Users/ashley/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/ashley/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/__main__.py", line 5, in <module>
    main.main()
  File "mosfit/main.py", line 483, in main
    Fitter().fit_events(**fitargs)
  File "mosfit/fitter.py", line 321, in fit_events
    check_upload_quality=check_upload_quality)
  File "mosfit/fitter.py", line 754, in fit_data
    realdict[REALIZATION.ALIAS] = str(ri)
AttributeError: class REALIZATION has no attribute 'ALIAS'

**Comment by guillochon** [comment]
Hey @villrv, update your astrocats package to the latest version.
