### ISSUE TITLE
error when fitting SN2005E

### ISSUE THREAD

**Issue by villrv** [guillochon/MOSFiT#78]
When fitting SN2005E (and other SNe with radio data?) with python2.7, there is a unicode error:

`
Finding bands...
Failed to execute module `resttimes`'s process().
Traceback (most recent call last):
  File "/Users/ashley/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/ashley/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/ashley/Programs/mosfit_git/MOSFiT/mosfit/__main__.py", line 5, in <module>
    main.main()
  File "mosfit/main.py", line 757, in main
    Fitter().fit_events(**fitargs)
  File "mosfit/fitter.py", line 482, in fit_events
    walker_data=walker_data)
  File "mosfit/fitter.py", line 604, in load_data
    root=root)
  File "mosfit/model.py", line 609, in run_stack
    new_outs = self._modules[task].process(**inputs)
  File "mosfit/modules/arrays/resttimes.py", line 21, in process
    x / (1.0 + kwargs['redshift']) for x in self._times
TypeError: unsupported operand type(s) for /: 'unicode' and 'float'
`

**Comment by guillochon** [comment]
With the current version this issue seems to have gone away (tested in both Python 2.7 & 3.6). @villrv could you verify at your earliest convenience?

**Comment by villrv** [comment]
Yup, this is working for me now
